In [1]:
import pandas as pd

df =pd.read_excel('员工加餐购买小程序_20251227090104.xlsx',header=[0,1])
df

              实例标题              下单时间   员工工号 员工姓名                   车间-工段  取餐点  \
              实例标题              下单时间   员工工号 员工姓名                   车间-工段  取餐点
0   匿名发起的员工加餐购买小程序  2025-12-26 09:05  39469  王平安   青岛焊装-生产二区域-前后盖工段-前后盖甲   H2
1   匿名发起的员工加餐购买小程序  2025-12-26 11:45  37734  秦政晓  青岛焊装-生产二区域-侧围工段-侧围内板甲班  G13
2   匿名发起的员工加餐购买小程序  2025-12-26 07:43  37390  代路平   青岛焊装-维修区域-维修工段乙-维修综合一   M4
3   匿名发起的员工加餐购买小程序  2025-12-26 08:05  39485  孙立伟   青岛焊装-生产一区域-下部二工段-补焊甲班   M9
4   匿名发起的员工加餐购买小程序  2025-12-26 08:05  39485  孙立伟   青岛焊装-生产一区域-下部二工段-补焊甲班   M9
..             ...               ...    ...  ...                     ...  ...
76  匿名发起的员工加餐购买小程序  2025-12-26 10:40  39639  徐国斌  青岛焊装-生产二区域-侧围工段-侧围内板甲班  G13
77  匿名发起的员工加餐购买小程序  2025-12-26 10:40  39639  徐国斌  青岛焊装-生产二区域-侧围工段-侧围内板甲班  G13
78  匿名发起的员工加餐购买小程序  2025-12-26 09:45  37406   杨松    青岛焊装-维修区域-维修工段甲-维修下部  G13
79  匿名发起的员工加餐购买小程序  2025-12-26 11:11  39687   杨阳   青岛焊装-生产二区域-前后盖工段-前后盖甲   H2
80  匿名发起的员工加餐购买小程序  2025-12-26 11:01  37956  杨洪凯     青岛焊装-生产二区域-四门工段-后门甲   H2

   购买明细           付款总金额                                             上传付款截图  \
     菜单 购买数量   单价 付款总金额                                             上传付款截图
0   蛋炒饭    1  2.0   2.0  https://www.aliwork.com/o/G1H662A1VTS1VPJTHTGV...
1   牛肉饼    2  4.0   8.0  https://www.aliwork.com/o/LPE66X61YDS1U2PMIKBK...
2   牛肉饼    2  4.0   8.0  https://www.aliwork.com/o/X8E66F71QES11NGYHAHP...
3   蛋炒饭    2  2.0   5.0  https://www.aliwork.com/o/0OE66QD1ASS18GFPHLQ2...
4   小咸菜    1  1.0   5.0  https://www.aliwork.com/o/0OE66QD1ASS18GFPHLQ2...
..  ...  ...  ...   ...                                                ...
76  蛋炒饭    1  2.0   7.0  https://www.aliwork.com/o/GHC66M91FSS1IB5JIE1Q...
77  小咸菜    1  1.0   7.0  https://www.aliwork.com/o/GHC66M91FSS1IB5JIE1Q...
78   玉米    1  3.0   3.0  https://www.aliwork.com/o/NZE66ID1RDS18E7GJZUJ...
79  蛋炒饭    2  2.0   4.0  https://www.aliwork.com/o/6Z966BA1VDS107VMIZGS...
80   麻花    1  3.5   3.5  https://www.aliwork.com/o/0V766PA1PDS1VC0YK5SU...

   提交人            提交人组织                 创建时间                 修改时间
   提交人            提交人组织                 创建时间                 修改时间
0   匿名  一汽—大众汽车有限公司合作伙伴  2025-12-26 09:09:13  2025-12-26 09:09:13
1   匿名  一汽—大众汽车有限公司合作伙伴  2025-12-26 11:47:20  2025-12-26 11:47:20
2   匿名  一汽—大众汽车有限公司合作伙伴  2025-12-26 07:45:02  2025-12-26 07:45:02
3   匿名  一汽—大众汽车有限公司合作伙伴  2025-12-26 08:06:17  2025-12-26 08:06:17
4   匿名  一汽—大众汽车有限公司合作伙伴  2025-12-26 08:06:17  2025-12-26 08:06:17
..  ..              ...                  ...                  ...
76  匿名  一汽—大众汽车有限公司合作伙伴  2025-12-26 10:41:40  2025-12-26 10:41:40
77  匿名  一汽—大众汽车有限公司合作伙伴  2025-12-26 10:41:40  2025-12-26 10:41:40
78  匿名  一汽—大众汽车有限公司合作伙伴  2025-12-26 09:46:11  2025-12-26 09:46:11
79  匿名  一汽—大众汽车有限公司合作伙伴  2025-12-26 11:11:58  2025-12-26 11:11:58
80  匿名  一汽—大众汽车有限公司合作伙伴  2025-12-26 11:01:53  2025-12-26 11:01:53

[81 rows x 15 columns]

In [9]:
df[('购买明细.2')]

0      单价
1       2
2       4
3       4
4       2
     ...
77      2
78      1
79      3
80      2
81    3.5
Name: 购买明细.2, Length: 82, dtype: object

In [11]:
df =pd.read_excel('sigma_export (96).xlsx')
df

,员工号,姓名,平台身份,业务种类,发生额,发生前库余额,发生后库余额,钱包类型,发生时间,所属食堂,POS机号,发生地
0,40318,张永斌,青岛正式工,消费,-11.0,1404.11,1393.11,补助钱包,2025-12-25 18:33:33,青岛管控中心二餐厅,YP_0031500001,青岛
1,32621,田 明,青岛正式工,消费,-20.0,2083.44,2063.44,补助钱包,2025-12-25 18:23:21,青岛管控中心二餐厅,YP_0031500001,青岛
2,37334,杨春贞,青岛正式工,消费,-5.5,1987.54,1982.04,补助钱包,2025-12-25 18:19:01,青岛管控中心二餐厅,YP_0031500001,青岛
3,01341,杨鲁平,青岛正式工,消费,-12.0,843.56,831.56,补助钱包,2025-12-25 18:16:16,青岛管控中心二餐厅,YP_0031500001,青岛
4,37315,时丕顺,青岛正式工,消费,-17.0,1037.01,1020.01,补助钱包,2025-12-25 18:14:22,青岛管控中心二餐厅,YP_0031500001,青岛
...,...,...,...,...,...,...,...,...,...,...,...,...
1405,37577,杨 振,青岛正式工,消费,-4.0,955.91,951.91,补助钱包,2025-12-25 07:25:34,青岛管控中心二餐厅,YP_0031500011,青岛
1406,102967,刘 伟,青岛正式工,消费,-7.0,1648.24,1641.24,补助钱包,2025-12-25 07:23:47,青岛管控中心二餐厅,YP_0031500011,青岛
1407,40675,郑世鑫,青岛正式工,消费,-3.0,3078.33,3075.33,补助钱包,2025-12-25 07:23:13,青岛管控中心二餐厅,YP_0031500002,青岛
1408,103380,于锡浩,青岛正式工,消费,-2.0,1952.43,1950.43,补助钱包,2025-12-25 07:20:41,青岛管控中心二餐厅,YP_0031500011,青岛
1409,40258,赵常远,青岛正式工,消费,-7.5,2223.31,2215.81,补助钱包,2025-12-25 07:20:26,青岛管控中心二餐厅,YP_0031500002,青岛

In [4]:
df =pd.read_excel('data/员工加餐购买小程序_20251228101936.xlsx',header=[0,1])
df

              实例标题              下单时间      员工工号 员工姓名                  车间-工段  \
              实例标题              下单时间      员工工号 员工姓名                  车间-工段
0   匿名发起的员工加餐购买小程序  2025-12-27 11:44   40844.0  甘洪志    青岛焊装-生产二区域-四门工段-后门甲
1   匿名发起的员工加餐购买小程序  2025-12-27 11:22   39729.0  陈远远  青岛焊装-生产三区域-装配工段-装配后部甲
2   匿名发起的员工加餐购买小程序  2025-12-27 11:22   39729.0  陈远远  青岛焊装-生产三区域-装配工段-装配后部甲
3   匿名发起的员工加餐购买小程序  2025-12-27 10:59   39454.0  计振东    青岛焊装-生产二区域-四门工段-后门甲
4   匿名发起的员工加餐购买小程序  2025-12-27 10:59   39454.0  计振东    青岛焊装-生产二区域-四门工段-后门甲
..             ...               ...       ...  ...                    ...
77  匿名发起的员工加餐购买小程序  2025-12-27 11:39   39577.0   鞠鑫  青岛焊装-生产一区域-下部一工段-补焊甲班
78  匿名发起的员工加餐购买小程序  2025-12-28 07:21   39694.0  熊红柠  青岛焊装-生产三区域-装配工段-装配后部甲
79  匿名发起的员工加餐购买小程序  2025-12-28 07:21   39694.0  熊红柠  青岛焊装-生产三区域-装配工段-装配后部甲
80  匿名发起的员工加餐购买小程序  2025-12-28 08:26  106131.0  赵宗瑞  青岛焊装-生产二区域-前后盖工段-前后盖甲
81  匿名发起的员工加餐购买小程序  2025-12-27 10:55   37699.0  石保领    青岛焊装-生产二区域-四门工段-前门甲

    取餐点   加餐明细           付款总金额  \
    取餐点     菜单 购买数量   单价 付款总金额
0    M9     麻花    1  3.5   3.5
1    M9  白象多半桶    1  4.5   7.0
2    M9     菜卷    1  2.5   7.0
3    H2     麻花    1  3.5   6.0
4    H2     菜卷    1  2.5   6.0
..  ...    ...  ...  ...   ...
77  G13    牛肉饼    1  4.0   8.5
78   M9    牛肉饼    1  4.0   7.0
79   M9     玉米    1  3.0   7.0
80   H2    牛肉饼    2  4.0   8.0
81   M4     菜卷    2  2.5   5.0

                                               上传付款截图 提交人            提交人组织  \
                                               上传付款截图 提交人            提交人组织
0   https://www.aliwork.com/o/IV966DA1QDS1METAGSAH...  匿名  一汽—大众汽车有限公司合作伙伴
1   https://www.aliwork.com/o/0OE66QD1RES1P8IKGJW3...  匿名  一汽—大众汽车有限公司合作伙伴
2   https://www.aliwork.com/o/0OE66QD1RES1P8IKGJW3...  匿名  一汽—大众汽车有限公司合作伙伴
3   https://www.aliwork.com/o/UB766P6154T1T878IQIP...  匿名  一汽—大众汽车有限公司合作伙伴
4   https://www.aliwork.com/o/UB766P6154T1T878IQIP...  匿名  一汽—大众汽车有限公司合作伙伴
..                                                ...  ..              ...
77  https://www.aliwork.com/o/LHC66T71X4T19O2BP4ZL...  匿名  一汽—大众汽车有限公司合作伙伴
78  https://www.aliwork.com/o/FHC66YC1K4T1YVOUKA7X...  匿名  一汽—大众汽车有限公司合作伙伴
79  https://www.aliwork.com/o/FHC66YC1K4T1YVOUKA7X...  匿名  一汽—大众汽车有限公司合作伙伴
80  https://www.aliwork.com/o/GHC66M91P4T1ZRBJIE8P...  匿名  一汽—大众汽车有限公司合作伙伴
81  https://www.aliwork.com/o/KPE66991P4T1OB15KHJ3...  匿名  一汽—大众汽车有限公司合作伙伴

                   创建时间                 修改时间
                   创建时间                 修改时间
0   2025-12-27 11:45:10  2025-12-27 11:45:10
1   2025-12-27 11:24:04  2025-12-27 11:24:04
2   2025-12-27 11:24:04  2025-12-27 11:24:04
3   2025-12-27 11:00:49  2025-12-27 11:00:49
4   2025-12-27 11:00:49  2025-12-27 11:00:49
..                  ...                  ...
77  2025-12-27 11:44:12  2025-12-27 11:44:12
78  2025-12-28 07:24:02  2025-12-28 07:24:02
79  2025-12-28 07:24:02  2025-12-28 07:24:02
80  2025-12-28 08:29:32  2025-12-28 08:29:32
81  2025-12-27 10:56:37  2025-12-27 10:56:37

[82 rows x 15 columns]

In [8]:
df.iat[0,0]

'匿名发起的员工加餐购买小程序'

In [9]:
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}
df = pd.DataFrame(data)
df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [10]:
df.iloc[0, 0]

'Alice'